---

- name: "Ensure apt mandatory packages are installed"
  apt:
    name: "{{ ranger_apt_mandatory_packages }}"
    state: present

- name: "Ensure apt optional packages are installed"
  apt:
    name: "{{ ranger_apt_optional_packages }}"
    state: present
  when: ranger_apt_install_optional_packages

- name: "Ensure apt enhancement packages are installed"
  apt:
    name: "{{ ranger_apt_enhancement_packages }}"
    state: present
  when: ranger_apt_install_enhancement_packages
