---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8-ranger-fm
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
