---

ranger_user_name: ak
ranger_user_group: ak
ranger_user_pass: test_pass

ranger_create_group: yes
ranger_create_user: yes

ranger_yum_mandatory_packages:
  - ncurses-devel      # for curses python module?
  - python3            #
  - less               # default pager

ranger_yum_install_optional_packages: yes
ranger_yum_optional_packages:
  - file               # for determining file types
  - sudo               # to use the "run as root" feature

ranger_yum_install_enhancement_packages: yes
ranger_yum_enhancement_packages:
  - lynx               # to preview html pages and images
  - jq                 # json parsing
  - tar                # for dealing with archives
