---

ranger_user_name: ak
ranger_user_group: ak
ranger_user_pass: test_pass

ranger_create_group: yes
ranger_create_user: yes

ranger_apt_mandatory_packages:
  - libncurses5-dev    # for curses python module?
  - libncursesw5-dev   # wide character support
  - python3            #
  - python3-pip        #
  - less               # default pager

ranger_apt_install_optional_packages: yes
ranger_apt_optional_packages:
  - file               # for determining file types
  - sudo               # to use the "run as root" feature

ranger_apt_install_enhancement_packages: yes
ranger_apt_enhancement_packages:
  - w3m                # to preview html pages and images
  - jq                 # json parsing
  - atool              # for dealing with archives
